### ISSUE TITLE
image contains empty /[data]/ directory

### ISSUE THREAD

**Issue by meonkeys** [peercoin/docker-peercoind#10]
I noticed in 0.9.0 that there's a directory under the root called `[data]`. This looks like the result of a typo, bug, or something failing during one of the build steps. I haven't noticed any adverse effects yet. Unless this is intentional and there's something I don't understand in the `Dockerfile`.

**Comment by peerchemist** [comment]
You mean this here:

https://github.com/peercoin/docker-peercoind/blob/master/0.9.0/Dockerfile#L91

**Comment by meonkeys** [comment]
Aha, that's related, good call. I think https://github.com/peercoin/docker-peercoind/blob/master/0.9.0/Dockerfile#L100 is where the mountpoint is actually created with square braces. It must be interpreting that value as a string instead of a one-element array. I'll test a bit and see if I can get a good patch worked out.
